### ISSUE TITLE
Filesystem backend: Add option to save decoded response content

### ISSUE THREAD

**Issue by aaronsteers** [requests-cache/requests-cache#631]
I want to have human-readable cache files so they can be more easily inspected and scrubbed for PII by humans.

The code I'm using now is:

```
    requests_cache.install_cache(
        cache_path_root,
        backend="filesystem",
        serializer="yaml",
        expire_after=24 * 60 * 60,
        # Important: make sure that API keys don't end up being cached:
        ignored_parameters=[API_TOKEN_KEY],        
    )
```

This is working well for us, except that the content is just a block of what looks like gzipped text.

Note below the sections `_content: !!binary |`, `Accept-Encoding: gzip, deflate`, `Content-Encoding: gzip`, and `decode_content: false`.

Is there any way to just have requests-cache decode my response data before caching? Or alternatively, can I disable gzip content encoding somehow in the response?

```
_content: !!binary |
  eyJpZCI6MjQwNzg4MDg1LCJpaWQiOjExMjgsInByb2plY3RfaWQiOjE4OTgzNTMwLCJzaGEiOiI0
  MzBjMmZhY2ZjOWIzZjBjNzBkYjZiOWViODc5YzJiNjY3MzFhZTM3IiwicmVmIjoibWFzdGVyIiwi
  c3RhdHVzIjoic3VjY2VzcyIsInNvdXJjZSI6InBpcGVsaW5lIiwiY3JlYXRlZF9hdCI6IjIwMjEt
  ...
created_at: '2022-05-10T00:48:18.136194'
elapsed: 0.189967
encoding: utf-8
expires: '2022-05-11T00:48:18.136181'
headers:
  CF-Cache-Status: DYNAMIC
  CF-RAY: 708eab21387602a7-SEA
  Cache-Control: max-age=0, private, must-revalidate
  Connection: keep-alive
  Content-Encoding: gzip
  Content-Type: application/json
  Date: Tue, 10 May 2022 00:48:18 GMT
  Etag: W/"c262e120dcdce5b0853ac3f47956239a"
  Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
  GitLab-LB: fe-02-lb-gprd
  GitLab-SV: localhost
  NEL: '{"success_fraction":0.01,"report_to":"cf-nel","max_age":604800}'
  RateLimit-Limit: '2000'
  RateLimit-Observed: '210'
  RateLimit-Remaining: '1790'
  RateLimit-Reset: '1652143758'
  RateLimit-ResetTime: Tue, 10 May 2022 00:49:18 GMT
  Referrer-Policy: strict-origin-when-cross-origin
  Report-To: '{"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v3?s=dcvwH6aN6%2By8Ds9FIRdE9dXkf0ygXPr7yBm%2FBeX7CL7zntTEjE1PCica6%2FT%2B6DatimLPdvdFz6f%2BmoP%2B5V7ziWAY%2FDHbYh4NoM%2BeYuqHpWBAk2mtRb9yZNgAw%2FI%3D"}],"group":"cf-nel","max_age":604800}'
  Server: cloudflare
  Strict-Transport-Security: max-age=31536000
  Transfer-Encoding: chunked
  Vary: Origin
  X-Content-Type-Options: nosniff
  X-Frame-Options: SAMEORIGIN
  X-Request-Id: 01G2NQ0C86W8YPTSBVN4NH5FC5
  X-Runtime: '0.056350'
raw:
  decode_content: false
  reason: OK
  status: 200
  version: 11
reason: OK
request:
  body: !!binary |
    Tm9uZQ==
  headers:
    Accept: '*/*'
    Accept-Encoding: gzip, deflate.  <<<<<<<
    Connection: keep-alive
    User-Agent: python-requests/2.27.1
  method: GET
  url: https://gitlab.com/api/v4/projects/18983530/pipelines/240788085?order_by=updated_at&page=57&sort=asc&updated_after=2010-01-01T00:00:00+00:00
status_code: 200
url: https://gitlab.com/api/v4/projects/18983530/pipelines/240788085?order_by=updated_at&page=57&sort=asc&updated_after=2010-01-01T00:00:00+00:00
```

**Comment by JWCook** [comment]
That content is just original response body as it's received from the server, which is needed to reconstruct the original response object when it comes back from the cache. There's a bit more of [an explanation on that here](https://stackoverflow.com/a/71775172/15592055). The main challenge is making sure that whatever comes back from the cache behaves exactly like the original response.

I think this is something I would be interested in adding, although I'm not quite sure about the best way to go about it yet. This could be either a separate optional serializer, or with a bit more work it could be the default behavior for the filesystem backend.

How do you think this should handle different `Content-Type` values? Should it just set the content as plaintext if it can be decoded as text? Or as a dict (or yaml mapping in this case) if it's `application/json`? And I'm guessing all other application, multipart, or media types would have to stay in binary format.

Then during deserialization, the content needs to be encoded back to bytes (if it isn't already); some features of [requests.Response](https://docs.python-requests.org/en/latest/api/#requests.Response) require the original raw response body. That's why it has multiple layers like the `.content` property, `._content` internal attribute, `.raw` response from urllib3, and `.raw.fp` file-like object. Hopefully that would be easy enough, although we may need to handle the `Content-Encoding` as well.

**Comment by JWCook** [comment]
Also, a somewhat related issue is #580. Are you interested in viewing/editing mainly just the response content, or content plus metadata (headers, etc.)?

**Comment by aaronsteers** [comment]
Hi, @JWCook. Thanks for the speedy reply! 😄 

In my case, all the headers/etc. are already appearing in clear text so it it is just the response content itself that I want to deobfuscate by skipping or decoding the gzip behavior before storing the cache artifact. In my issue body above, the headers and all other metadata appear to have very good and human-readable content when using the `yaml` backend. My only concern is the `_content` attribute being binary. (And for my part, I don't so much mind if they are in the same/separate files. It seems having them in the same yaml file may actually be more convenient for my case.)

Thanks again!

**Comment by aaronsteers** [comment]
@JWCook - UPDATE to the above, after reading your first comment more carefully, and also the SO answer you helpfully posted, I can see there are some available workarounds here. For my use case, I think the answer you posted to SO could do the trick.

And I understand your point regarding how the cached data needs to still match the original format. And I guess, it's always nice to hear there isn't just an obvious answer or solution I was missing due to my more limited experience. 😄 

One possible feature option I can see (although perhaps not super performance) might be to allow the backends an option to _redundantly_ store a decoded version of the response data if something like `gzip` encoding is detected. This admittedly sacrifices performance and storage cost for a more transparent and consumable cache layer.

**Comment by JWCook** [comment]
> to have robust CI/CD pipelines and "demo modes" that doesn't require connecting to the source API and would not require providing credentials. One way to accomplish this is to commit the source API's cache results back to the repo, but this requires a high confidence that we aren't inadvertently committing back any secrets or PII.

Very interesting use case! I should also mention that the libraries [betamax](https://betamax.readthedocs.io) and [vcrpy](https://vcrpy.readthedocs.io) are other candidates for "replaying" responses, but they also serialize response content as binary, for the same reasons.

After thinking this over a bit more, I have some ideas for doing this without duplicating content. I can probably get to this sometime within the next couple weeks.

**Comment by JWCook** [comment]
@aaronsteers
FYI, there are some changes to support this in `main` (see #647 for details). The behavior may change a bit before 1.0 is released, but you can enable it with the `decode_content` argument:
```python
from requests_cache import CachedSession
session = CachedSession(
    'example_cache',
    backend='filesystem',
    serializer='yaml',
    decode_content=True,
)
session.get('https://httpbin.org/json')
```

The resulting file looks like:
```yaml
_decoded_content:                           
  slideshow:                                
    author: Yours Truly                     
    date: date of publication               
    slides:                                 
    - title: Wake up to WonderWidgets!      
      type: all                             
    - items:                                
      - Why <em>WonderWidgets</em> are great
      - Who <em>buys</em> WonderWidgets     
      title: Overview                       
      type: all                             
    title: Sample Slide Show                
created_at: '2022-06-10T21:27:55.746096'    
elapsed: 0.274172                           
encoding: utf-8                             
headers:                                    
  Access-Control-Allow-Credentials: 'true'  
  Access-Control-Allow-Origin: '*'          
  Connection: keep-alive                    
  Content-Length: '429'                     
  Content-Type: application/json            
  Date: Fri, 10 Jun 2022 21:27:55 GMT       
  Server: gunicorn/19.9.0                   
raw:                                        
  decode_content: false                     
  reason: OK                                
  status: 200                               
  version: 11                               
reason: OK                                  
request:                                    
  body: !!binary |                          
    Tm9uZQ==                                
  headers:                                  
    Accept: '*/*'                           
    Accept-Encoding: gzip, deflate    
    Connection: keep-alive            
    User-Agent: python-requests/2.28.0
  method: GET                         
  url: https://httpbin.org/json       
status_code: 200                      
url: https://httpbin.org/json         
```

The content is stored in a separate `_decoded_content`, which is a small compromise so other parts of the library can always assume `_content` is binary if present.

By the way, that `raw.decode_content` value in the response file is from [urllib3.HTTPResponse](https://urllib3.readthedocs.io/en/stable/reference/urllib3.response.html#urllib3.response.HTTPResponse), and unrelated to serialization.

So far it seems efficient enough that I'm considering making it the default behavior for the filesystem backend. Test it out when you get the chance, and let me know if you run into any issues or have more suggestions.
