### ISSUE TITLE
Doesn't work in Github Workflows/Actions

### ISSUE THREAD

**Issue by Arthavruksha** [requests-cache/requests-cache#663]
### The problem
So when i run Requests_Cache in my Local Machine an .sqlite file is automatically formed and caching is started directly as all requests are added in that .sqlite file. Although when i run the same code in Github Workflows/Actions this .sqlite file isn't formed even though i have defined (backend='sqlite') in the Code and thus caching doesn't happen

### Expected behavior
_I expected that a .sqlite file should get formed in the Repository and Caching should start happening

### Steps to reproduce the behavior
Here's the code from my actual python file
`session = requests_cache.CachedSession('demo_cache',use_cache_dir=True,backend='sqlite')`

And here's my .yml file code that runs in Github Workflows/Actions
`name: Corporate Announcements

on:
  schedule:
    - cron: '0 * * * *' # 

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:

      - name: checkout repo content
        uses: actions/checkout@v3 # checkout the repository content to github runner
      - uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9' # install the python version needed
          cache: 'pip'
          cache-dependency-path: 'ca-requirements.txt'
          
      - name: install python packages
        run: pip install -r ca-requirements.txt
          
      - name: execute py script
        run: python announcementsv2.py`

### Workarounds
I am not aware of 

### Environment
- requests-cache version: (Latest Version)
- Python version: ( `3.9`)
- Platform: Github workflows

**Comment by JWCook** [comment]
I see. `use_cache_dir=True` may be the problem there. In a GitHub Actions runner, you may not have access to create new directories in `~/.cache`. For any files you create/modify in a workflow, it's best to keep them in the CI project directory.

Try this and see if that helps:
```python
session = requests_cache.CachedSession('demo_cache', backend='sqlite')
```

That should create a `demo_cache.sqlite` file in the current directory. And I believe you could also use `actions/cache` to persist that across multiple workflows, if you wanted (although I haven't tested that myself).

**Comment by Arthavruksha** [comment]
Will try this

**Comment by Arthavruksha** [comment]
Hi this method also isn't working . What should I do now ?

**Comment by Arthavruksha** [comment]
Well this also doesn't work , what should I do now ?

**Comment by Arthavruksha** [comment]
Yo @JWCook Any solutions u found on this topic ?

**Comment by JWCook** [comment]
I just tested requests-cache with GitHub actions, and I wasn't able to reproduce any problems. I added some [example config here](https://github.com/requests-cache/requests-cache/blob/main/examples/github_actions.yml) that runs [this example script](https://github.com/requests-cache/requests-cache/blob/main/examples/basic_sessions.py) and stores the `.sqlite` file for future workflow runs.

So I don't have enough information to tell what the problem is. It could be something within that `announcementsv2.py` file. Try [enabling debug logs](https://requests-cache.readthedocs.io/en/stable/user_guide/troubleshooting.html#logging) and see if that provides any useful info.

**Comment by Arthavruksha** [comment]
Okay Will check it out today and let you know

**Comment by Arthavruksha1** [comment]
Hi JWCook this is my another account, Its still not creating any file at my end

Why are u running the python script 2 times in .yml file ?

This is my updated .yml file

```
name: Corporate Announcements

on:
  schedule:
    - cron: '0 * * * *' # 

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - id: cache
        uses: actions/cache@v3
        with:
         path: demo_cache.sqlite
         key: none

      - name: checkout repo content
        uses: actions/checkout@v3 # checkout the repository content to github runner
      - uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9' # install the python version needed
          cache: 'pip'
          cache-dependency-path: 'ca-requirements.txt'
          
      - name: install python packages
        run: pip install -r ca-requirements.txt
          
      - name: execute py script
        run: python announcementsv2.py`
```

And u were asking that `announcementsv2.py` might have some error. This is the part of the .py script which has requests in it 

`def smeca():   
    print("Started Pulling")
    currentd = date.today()
    s = requests_cache.CachedSession('demo_cache', backend='sqlite')
    headers =   {'Host':'www.nseindia.com','User-Agent':'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:82.0) Gecko/20100101 Firefox/82.0','Accept':'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8', 'Accept-Language':'en-US,en;q=0.5', 'Accept-Encoding':'gzip, deflate, br','DNT':'1', 'Connection':'keep-alive', 'Upgrade-Insecure-Requests':'1','Pragma':'no-cache','Cache-Control':'no-cache',  }
    url = 'https://www.nseindia.com/'
    step = s.get(url,headers=headers)`

And after that the code ends. Is their anything i am doing wrong

**Comment by JWCook** [comment]
And did you enable debug logs? That will tell you when headers or other settings disable caching for a request.

**Comment by Arthavruksha1** [comment]
Removed  'Cache-Control':'no-cache' from code sir although still nothing is happening , Will try with enabling debug logs

**Comment by Arthavruksha1** [comment]
Hey JWCook i have figured out the way to scrape it without the header parameter . Will test it out tommorrow

**Comment by Arthavruksha1** [comment]
And this is how my .yml file looks like . Do let me know if this has something which is preventing caching

```
name: Corporate Announcements

on:
  schedule:
    - cron: '0 * * * *' # 

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - id: cache
        uses: actions/cache@v3
        with:
         path: demo_cache.sqlite
         key: none

      - name: checkout repo content
        uses: actions/checkout@v3 # checkout the repository content to github runner
      - uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9' # install the python version needed
          cache: 'pip'
          cache-dependency-path: 'ca-requirements.txt'
          
      - name: install python packages
        run: pip install -r ca-requirements.txt
          
      - name: execute py script
        run: python announcementsv2.py
```
